#!/usr/local/bin/zsh

[[ -f scanmon.log ]] && rm scanmon.log

python3 scanmon.py $* 2>error.log
stty sane		# Just in case

logs=()

[[ -s error.log ]] && logs=(error.log)
[[ -s scanmon.log ]] && logs=($logs scanmon.log)

[[ $#logs > 0 ]] && less $logs
